/**
 * SpaceX Launches API
 * REST API documentation for the SpaceX Launches system
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Launch { 
    createdAt: object;
    id: number;
    tag: string;
    updatedAt: object;
    articleUrl: string;
    badgeUrl: string;
    launchDate: object;
    launchDetails: string;
    launchNumber: number;
    reddit: boolean;
    reused: boolean;
    rocketName: string;
    rocketType: string;
}

